<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_radius" value="0.225"/>
    <xacro:property name="chassis_height" value="0.15"/> <xacro:property name="chassis_mass" value="2.0"/>
    
    <xacro:property name="wheel_radius" value="0.04"/> <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.2"/>
    
    <xacro:property name="wheel_offset_y" value="0.235"/> 
    <xacro:property name="caster_wheel_radius" value="0.025"/>
    <xacro:property name="caster_wheel_mass" value="0.05"/>
    <xacro:property name="caster_offset_x" value="0.180"/>

    <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
    <material name="blue"><color rgba="0.2 0.2 1 1"/></material>
    <material name="white"><color rgba="1 1 1 1" /></material>
    <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>

    <link name="base_link"></link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="base_footprint"></link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius}"/> 
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_height}" radius="${chassis_radius}">
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <gazebo reference="chassis">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} ${wheel_radius}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} ${wheel_radius}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="front_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="front_caster_wheel"/>
        <origin xyz="${caster_offset_x} 0 ${caster_wheel_radius - wheel_radius}"/>
    </joint>

    <link name="front_caster_wheel">
        <visual>
            <origin xyz="0 0 0.01" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.04"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="0.015"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry><sphere radius="${caster_wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <joint name="rear_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="rear_caster_wheel"/>
        <origin xyz="${-caster_offset_x} 0 ${caster_wheel_radius - wheel_radius}"/>
    </joint>

    <link name="rear_caster_wheel">
        <visual>
            <origin xyz="0 0 0.01" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.04"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="0.015"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry><sphere radius="${caster_wheel_radius}"/></geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    
    <gazebo reference="front_caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/><mu2 value="0.001"/>
    </gazebo>
    <gazebo reference="rear_caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/><mu2 value="0.001"/>
    </gazebo>

</robot>